---
title: "GIS"
author: "Amardeep Singh"
date: "June 30, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
install.packages("tmap")
```
```{r}
install.packages("rgdal")
install.packages("raster")
install.packages("rgeos")
```
```{r}
destfile <- "C://Users//Amardeep//Downloads//mdt_data2.csv"
plastic_data <- read.csv(file=destfile,header = TRUE)
```
```{r}
pl<-read.csv("C://Users//Amardeep//Downloads//PL//mdt_data (2).csv",header = TRUE)
ItemName<- pl$ListName
LogID<-pl$LogID
Latitude<-pl$Latitude
Longitude<-pl$Longitude
Altitude<-pl$Longitude
Quantity<-pl$Quantity
Location<-pl$Location
Description<-pl$Description
Material_ID<-pl$Material.ID
Material_Description<-pl$Material.Description
```
```{r}
rpivotTable::rpivotTable(pl,rows="ItemName",col=c("Quantity","Material.Description"))
```
```{r}
output$pivot <- renderRpivotTable({
 rpivotTable(data = pl , rows = c( "ItemName"),cols="Quantity",
 vals = "Quantity", aggregatorName = "Sum", rendererName = "Table",
 width="100%", height="500px")
 })

```
```{r}
Latitude
```
```{r}
library(maps) 
library(mapdata) 
library(maptools)
library(rgdal)
library(ggmap)
library(leaflet)
library(tigris)
library(sp)
library(ggplot2)
library(plyr)
library(animation)
library(gridExtra)
library(psych)
library(rstudioapi)
library(data.table)
```
```{r}
register_google(key = "AIzaSyBQDwI5PQuVwgm_T2UapE5QpD4hkRVAz-8")
map3 <- get_map(location = c(lon=-77.0259,lat=38.88942),
               maptype = "terrain", source = c("google", "osm", "stamen"),
               crop = FALSE,
               zoom = 15)
```
```{r}
sb <- readOGR("C://Users//Amardeep//Downloads//PL")
```
```{r}
library("tmap")
library("rgdal")
library("raster")
library("rgeos")
```
```{r}
mdf <- readOGR("C://Users//Amardeep//Desktop//INTERNSHIP//data//DATA")
```
```{r}
qtm(mdf)
```
```{r}
dem <- raster("C://Users//Amardeep//Desktop//INTERNSHIP//data//Data//DEM.img")
tm_shape(dem) + tm_raster(palette = "Greys", n=8) +
  tm_legend(outside = TRUE, text.size = .8)
```
```{r}
qtm(mdf, fill="Violent_rate", fill.style="pretty", title="Violent crimes \nper 100,000", legend.outside=TRUE)

```
```{r}
qtm(mdf, fill="Income")

```
```{r}
slope  <- terrain(dem, opt='slope')
aspect <- terrain(dem, opt='aspect')
hill   <- hillShade(slope, aspect, 40, 270)
tm_shape(hill) + tm_raster(palette = "Greys", style="cont", contrast = c(0,.8)) +
  tm_legend(show=FALSE) 
hill_me <- mask(hill, dem)
tm_shape(hill_me) + tm_raster(palette = "Greys", style="cont", contrast = c(0,.8)) +
  tm_legend(show=FALSE) 
```
```{r}
tm_shape(mdf) + 
  tm_fill("Income", style="fixed", breaks=c(0,23000 ,27000,100000 ),
          labels=c("under $23,000", "$23,000 to $27,000", "above $27,000"),
          palette="Greens")  +
  tm_borders("grey") +
  tm_legend(outside = TRUE, text.size = .8) +
  tm_layout(frame = FALSE) +
  tm_shape(hill_me) + tm_raster(palette = "Greys", style="cont", 
                                contrast = c(0,.8), alpha=0.4, 
                                 legend.show = FALSE) 
```
```{r}
mdf$Cutoff <- ifelse( mdf$Income > 23000, 1, 0)
qtm(mdf, fill="Cutoff", fill.style="cat")
```
```{r}
library("rworldmap")
# Get the world map
worldMap <- getMap()

# Member States of the European Union
europeanUnion <- c("Austria","Belgium","Bulgaria","Croatia","Cyprus",
                   "Czech Rep.","Denmark","Estonia","Finland","France",
                   "Germany","Greece","Hungary","Ireland","Italy","Latvia",
                   "Lithuania","Luxembourg","Malta","Netherlands","Poland",
                   "Portugal","Romania","Slovakia","Slovenia","Spain",
                   "Sweden","United Kingdom")
# Select only the index of states member of the E.U.
indEU <- which(worldMap$NAME%in%europeanUnion)

```
```{r}
# Extract longitude and latitude border's coordinates of members states of E.U. 
europeCoords <- lapply(indEU, function(i){
  df <- data.frame(worldMap@polygons[[i]]@Polygons[[1]]@coords)
  df$region =as.character(worldMap$NAME[i])
  colnames(df) <- list("long", "lat", "region")
  return(df)
})

europeCoords <- do.call("rbind", europeCoords)
```
```{r}
# Add some data for each member
value <- sample(x = seq(0,3,by = 0.1), size = length(europeanUnion),
                replace = TRUE)
europeanUnionTable <- data.frame(country = europeanUnion, value = value)
europeCoords$value <- europeanUnionTable$value[match(europeCoords$region,europeanUnionTable$country)]
```
```{r}
# Plot the map
P <- ggplot() + geom_polygon(data = europeCoords, aes(x = long, y = lat, group = region, fill = value),
                             colour = "black", size = 0.1) +
  coord_map(xlim = c(-13, 35),  ylim = c(32, 71))

P <- P + scale_fill_gradient(name = "Growth Rate", low = "#FF0000FF", high = "#FFFF00FF", na.value = "grey50")


P <- P + theme(#panel.grid.minor = element_line(colour = NA), panel.grid.minor = element_line(colour = NA),
               #panel.background = element_rect(fill = NA, colour = NA),
               axis.text.x = element_blank(),
               axis.text.y = element_blank(), axis.ticks.x = element_blank(),
               axis.ticks.y = element_blank(), axis.title = element_blank(),
               #rect = element_blank(),
               plot.margin = unit(0 * c(-1.5, -1.5, -1.5, -1.5), "lines"))
```
